#!/usr/bin/env python3
"""Write figures/INDEX.md per chapter and check figures against their scripts.

For every chapter it lists the figures in figures/, in book order, together
with the script that produces each one, and reports two kinds of mismatch:

  ORPHAN   a .png in figures/ that no script writes — stale, or hand-made
  MISSING  a script writes a figure that is not in figures/ — never run, or
           it failed

    python tools/make_figure_index.py
    python tools/make_figure_index.py --check   # report only, write nothing
"""

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
# Filenames appear both as plain strings and inside f-strings such as
# f"{OUT}/fig4_5_pq_heatmap.png", so match the name wherever it occurs.
PNG = re.compile(r"([A-Za-z0-9_.\-]+\.png)")
NUM = re.compile(r"fig[_]?(\d+)[._](\d+)", re.I)


def sort_key(name):
    """Order by the figure number in the filename, e.g. fig16_2 before fig16_10."""
    m = NUM.search(name)
    return (0, int(m.group(1)), int(m.group(2))) if m else (1, 0, 0)


def generated_by(chapter_dir):
    """{figure filename: script that writes it}"""
    out = {}
    for script in sorted(chapter_dir.glob("figures/generate_figures*.py")):
        for name in PNG.findall(script.read_text()):
            out.setdefault(name, script.name)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    problems = 0
    for chapter_dir in sorted(ROOT.glob("Chapter[0-9][0-9]")):
        fig_dir = chapter_dir / "figures"
        if not fig_dir.is_dir():
            continue
        present = sorted((p.name for p in fig_dir.glob("*.png")), key=sort_key)
        produced = generated_by(chapter_dir)

        orphans = [n for n in present if n not in produced]
        missing = [n for n in sorted(produced, key=sort_key) if n not in present]
        for n in orphans:
            # Hand-made figures (tables, diagrams) are legitimate; flag them so
            # they are re-checked by hand when the code behind them changes.
            print(f"HAND-MADE {chapter_dir.name}/figures/{n} — no script writes it")
        for n in missing:
            print(f"MISSING  {chapter_dir.name}/figures/{n} — {produced[n]} writes it")
            problems += 1

        if args.check or not present:
            continue

        lines = [f"# {chapter_dir.name} — figures", "",
                 "Generated by `tools/make_figure_index.py`. Regenerate the "
                 "figures with:", "",
                 "```bash",
                 f"cd {chapter_dir.name}",
                 "python figures/generate_figures.py",
                 "```", "",
                 "| Figure | File | Generated by |",
                 "| --- | --- | --- |"]
        for name in present:
            m = NUM.search(name)
            label = f"{int(m.group(1))}.{int(m.group(2))}" if m else "—"
            source = f"`{produced[name]}`" if name in produced else "by hand"
            lines.append(f"| {label} | `{name}` | {source} |")
        (fig_dir / "INDEX.md").write_text("\n".join(lines) + "\n")
        print(f"{chapter_dir.name}/figures/INDEX.md  ({len(present)} figure)")

    print(f"\n{problems} incoerenze (le figure 'by hand' non sono errori)")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
